### ISSUE TITLE
Error during build writeStatic

### ISSUE THREAD

**Issue by rifkidhan** [pluvial/svelte-adapter-deno#29]
Hello,

I'm tried to build my apps with latest sveltekit and get this error :
```
> Using svelte-adapter-deno
error during build:
Error: writeStatic has been removed. Please ensure you are using the latest version of svelte-adapter-deno
    at Object.writeStatic (file:///home/rifkidhan/Rifki/web/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.405_svelte@3.49.0+vite@3.0.5/node_modules/@sveltejs/kit/dist/chunks/index3.js:211:10)
    at adapt (file:///home/rifkidhan/Rifki/web/node_modules/.pnpm/svelte-adapter-deno@0.6.2/node_modules/svelte-adapter-deno/index.js:39:12)
    at adapt (file:///home/rifkidhan/Rifki/web/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.405_svelte@3.49.0+vite@3.0.5/node_modules/@sveltejs/kit/dist/chunks/index3.js:255:8)
    at Object.closeBundle (file:///home/rifkidhan/Rifki/web/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.405_svelte@3.49.0+vite@3.0.5/node_modules/@sveltejs/kit/dist/vite.js:2407:11)
    at async Promise.all (index 0)
    at async Object.close (file:///home/rifkidhan/Rifki/web/node_modules/.pnpm/rollup@2.77.3/node_modules/rollup/dist/es/shared/rollup.js:23662:13)
    at async Promise.all (index 0)
    at async build (file:///home/rifkidhan/Rifki/web/node_modules/.pnpm/vite@3.0.5/node_modules/vite/dist/node/chunks/dep-5cb728cb.js:43408:13)
    at async CAC.<anonymous> (file:///home/rifkidhan/Rifki/web/node_modules/.pnpm/vite@3.0.5/node_modules/vite/dist/node/cli.js:747:9)
 
```
When i'm tried delete this line, build success.

https://github.com/pluvial/svelte-adapter-deno/blob/c8a8ad87457d8988422781df0d467ec92d7406f7/index.js#L39

Thanks.

**Comment by jpaquim** [comment]
Should be fixed, let me know if you still have any problems @rifkidhan
